import dbConnect from "../../../lib/dbConnect";
import Teacher from "../../../models/teacher";
import { NextRequest, NextResponse } from "next/server";

dbConnect();
export async function POST(request: NextRequest) {
  try {
    const reqBody = await request.json();
    const {
      school,
      udise,
      tname,
      gender,
      ph,
      desig,
      fname,
      circle,
      sis,
      gp,
      association,
      phone,
      email,
      dob,
      doj,
      dojnow,
      dor,
      bank,
      account,
      ifsc,
      empid,
      training,
      pan,
      address,
      basic,
      mbasic,
      prevmbasic,
      addl,
      da,
      mda,
      hra,
      mhra,
      ma,
      gross,
      mgross,
      gpf,
      gpfprev,
      mptax,
      jptax,
      gsli,
      netpay,
      mnetpay,
      bonus,
      arrear,
      question,
      hoi,
      newHt,
      showAccount,
      service,
      id,
      rank,
      dataYear,
    }: any = reqBody;

    const newTeacher = new Teacher({
      school,
      udise,
      tname,
      gender,
      ph,
      desig,
      fname,
      circle,
      sis,
      gp,
      association,
      phone,
      email,
      dob,
      doj,
      dojnow,
      dor,
      bank,
      account,
      ifsc,
      empid,
      training,
      pan,
      address,
      basic,
      mbasic,
      prevmbasic,
      addl,
      da,
      mda,
      hra,
      mhra,
      ma,
      gross,
      mgross,
      gpf,
      gpfprev,
      mptax,
      jptax,
      gsli,
      netpay,
      mnetpay,
      bonus,
      arrear,
      question,
      hoi,
      newHt,
      showAccount,
      service,
      id,
      rank,
      dataYear,
    });
    const savedTeacher = await newTeacher.save();

    return NextResponse.json(
      {
        message: "Teacher saved successfully",
        success: true,
      },
      { status: 200 }
    );
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
