import mongoose from "mongoose";

const teacherSchema = new mongoose.Schema(
  {
    sl: String,
    school: String,
    udise: String,
    tsname: String,
    tname: String,
    desig: String,
    disability: String,
    circle: String,
    sis: String,
    gp: String,
    association: String,
    phone: String,
    email: String,
    dob: String,
    doj: String,
    dojnow: String,
    dor: String,
    bank: String,
    account: String,
    ifsc: String,
    empid: String,
    training: String,
    pan: String,
    aadhaar: String,
    address: String,
    basi: Number,
    mbasic: Number,
    addl: Number,
    da: Number,
    mda: Number,
    hra: Number,
    mhra: Number,
    ma: Number,
    gross: Number,
    mgross: Number,
    gpf: Number,
    gpfm: Number,
    gpfd: Number,
    ptax: Number,
    gsli: Number,
    netpay: Number,
    mnetpay: Number,
    netpayword: String,
    bonus: Number,
    arrear: Number,
    lic: Number,
    ppf: Number,
    hloanprincipal: Number,
    hloaninterest: Number,
    nsc: Number,
    mediclaim: Number,
    ph: String,
    fname: String,
    level: String,
    cell: String,
    tds: Number,
    question: String,
    hoi: String,
    service: String,
  },
  {
    timestamps: true,
  }
);

const Teacher =
  mongoose.models.teacher ||
  mongoose.model("teacher", teacherSchema, "teacher");

export default Teacher;
